flink:
  image: flink:1.18
  version: v1_18
  name: flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink
  job:
    name: kafka-to-iceberg-job
    uri: https://github.com/steadforce/flink-job/releases/download/22/flink_job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless
    args:
    - --NESSIE_HOST http://nessie.nessie.svc.cluster.local:19120/api/v1
    - --MINIO_HOST http://minio.minio.svc.cluster.local:80
    - --WAREHOUSE s3a://sensor/flink

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: flink