flink:
  image: flink:1.18
  version: v1_18
  name: &flink-name flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: *flink-name