flink:
  image: ghcr.io/steadforce/steadops/workbenches/flink-steadforce:sha-539c388
  version: v1_18
  name: flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  env:
    AWS_REGION: 
      value: us-east-1
    NESSIE_HOST: 
      value: http://nessie.nessie.svc.cluster.local:19120/api/v1
    MINIO_HOST: 
      value: http://minio.minio.svc.cluster.local:80
    MINIO_ACCESS_KEY: 
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: accesskey
    MINIO_SECRET_KEY:
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: secretkey
    WAREHOUSE: 
      value: s3a://sensor/flink
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink
  job:
    name: kafka-to-iceberg-job
    uri: https://github.com/steadforce/flink-job/releases/download/24/flink_job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: flink