flink:
  image: ghcr.io/steadforce/steadops/workbenches/flink-steadforce:sha-539c388
  version: v1_18
  name: flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  env:
    FLINK_PROPERTIES:
      value: |-
      s3.path.style.access: true
    AWS_REGION: 
      value: us-east-1
    NESSIE_HOST: 
      value: http://nessie.nessie.svc.cluster.local:19120/api/v1
    MINIO_HOST: 
      value: http://minio.minio.svc.cluster.local:80
    AWS_ACCESS_KEY_ID: 
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: accesskey
    AWS_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: secretkey
    WAREHOUSE: 
      value: s3a://sensor/flink
    KAFKA_BOOTSTRAP_SERVERS:
      value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
    KAFKA_TOPIC:
      value: steadforce.tools
    KAFKA_SCHEMA_REGISTRY_URL:
      value: http://kafka-schema-registry.kafka.svc.cluster.local:8081
    KAFKA_CONSUMER_GROUP:
      value: demo-consumer-group
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink
  job:
    name: kafka-to-iceberg-job
    uri: https://github.com/steadforce/flink-job/releases/download/26/flink_job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: flink