flink:
  image: ghcr.io/steadforce/steadops/workbenches/flink-steadforce:sha-539c388
  version: v1_18
  name: flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  env:
    ENABLE_BUILT_IN_PLUGINS:
      value: flink-s3-fs-hadoop-1.18.1.jar
    AWS_REGION: 
      value: us-east-1
    NESSIE_HOST: 
      value: http://nessie.nessie.svc.cluster.local:19120/api/v1
    S3_ENDPOINT:
      value: http://minio.minio.svc.cluster.local:80
    AWS_ACCESS_KEY_ID: 
      valueFrom:
        secretKeyRef:
          name: steadops-playground-bucket-user-mirror
          key: accesskey
    AWS_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: steadops-playground-bucket-user-mirror
          key: secretkey
    WAREHOUSE: 
      value: s3a://steadops-playground-bucket
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink
  job:
    name: kafka-to-iceberg-job
    uri: https://github.com/steadforce/flink-job/releases/download/36/flink_job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: flink