flink:
  image: flink:1.18
  version: v1_18
  name: flink-session-cluster
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  rbac:
    labels:
      app.kubernetes.io/name: flink-kubernetes-operator
      app.kubernetes.io/version: 1.0.1
    serviceAccount:
      name: flink
    role:
      name: flink
    roleBinding:
      name: flink
  job:
    name: kafka-to-iceberg-job
    uri: https://github.com/steadforce/flink-job/releases/download/12/flink_job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless

global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: flink