{{- if .Capabilities.APIVersions.Has "flink.apache.org/v1beta1" }}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Values.flink.name }}
spec:
  image: {{ .Values.flink.image }}
  flinkVersion: {{ .Values.flink.version }}
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: ENABLE_BUILT_IN_PLUGINS
              value: flink-s3-fs-hadoop-1.18.1.jar
  jobManager:
    resource:
    {{- toYaml .Values.flink.jobManager.resource | nindent 6}}
  taskManager:
    resource:
    {{- toYaml .Values.flink.taskManager.resource | nindent 6}}
{{- end }}