{{- if .Capabilities.APIVersions.Has "flink.apache.org/v1beta1" }}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-deployment
spec:
  image: {{ .Values.flink.image }}
  flinkVersion: {{ .Values.flink.version }}
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
    {{- toYaml .Values.flink.jobManager.resource | nindent 6}}
  taskManager:
    resource:
    {{- toYaml .Values.flink.taskManager.resource | nindent 6}}
{{- end }}