{{- if .Capabilities.APIVersions.Has "flink.apache.org/v1beta1" }}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Values.flink.name }}
spec:
  image: {{ .Values.flink.image }}
  flinkVersion: {{ .Values.flink.version }}
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    s3.path.style.access: "true"
    s3.endpoint: "http://minio.minio.svc.cluster.local:80"
    s3.endpoint.region: "us-east-1"
    fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    fs.s3a.access.key: "LLKhAHBakJ7d8HoS"
    fs.s3a.secret.key: "aewPMf5OiTzxKFFGPkxQYppkCjJPxGLq"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
             {{- range $name, $item := .Values.flink.env }}
            - name: {{ $name }}
              {{- $item | toYaml | nindent 14 }}
            {{- end }}
  jobManager:
    resource:
    {{- toYaml .Values.flink.jobManager.resource | nindent 6}}
  taskManager:
    resource:
    {{- toYaml .Values.flink.taskManager.resource | nindent 6}}
{{- end }}