apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- toYaml .Values.flink.rbac.labels | nindent 4}}
  name: {{ .Values.flink.rbac.role.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'